### obteter todas las tareas 
GET http://localhost:3000/api/tareas

### obteter una tarea 
GET http://localhost:3000/api/tareas/1

### crear una nueva tarea
POST http://localhost:3000/api/tareas
Content-Type: application/json

{
    "id": "10",
    "materia": "Fisica",
    "fechaentrega": "03/09/2025",
    "numerotarea": "6"
}


### modificar un atrubuto de una tarea
PATCH http://localhost:3000/api/tareas/2
Content-Type: application/json

{
    "fechaentrega": "23/02/2025"
}

### borrar una tarea
DELETE http://localhost:3000/api/tareas/1